__title__ = "mijiaAPI"
__version__ = "1.1.1"
__description__ = "A Python API for Xiaomi Mijia"
__url__ = "https://github.com/Do1e/mijia-api"
__author__ = "Do1e"
__author_email__ = "dpj.email@qq.com"
__license__ = "GPLv3"
