sid = 'xiaomiio'
msgURL = f'https://account.xiaomi.com/pass/serviceLogin?sid={sid}&_json=true'
loginURL = 'https://account.xiaomi.com/pass/serviceLoginAuth2'
qrURL = 'https://account.xiaomi.com/longPolling/loginUrl'
apiURL = 'https://api.io.mi.com/app'
deviceURL = 'https://home.miot-spec.com/spec/'
accountURL = 'https://account.xiaomi.com/pass2/profile/home?bizFlag=&userId='
